ARG WORK_DIR
ARG NODE_VERSION

FROM node:$NODE_VERSION

WORKDIR $WORK_DIR

RUN apk update && \
    apk add --no-cache nano bash htop && \
    npm install -g nodemon


COPY ./app/package*.json ./
RUN npm install
COPY ./app ./

CMD npm run dev